export const types = {
    OPEN_SNACKBAR: "OPEN_SNACKBAR",
    CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
    SET_DASHBOARD_DRAWER: "SET_DASHBOARD_DRAWER",
    START_UPDATING_TEAMS: "START_UPDATING_TEAMS",
    FINISH_UPDATING_TEAMS: "FINISH_UPDATING_TEAMS",
    ERROR_UPDATING_TEAMS: "ERROR_UPDATING_TEAMS",
    ADD_TO_TEAM: "ADD_TO_TEAM",
};
